file=open("exercises/first_file.text","w")
file.write("hello.\n")
file.write("I'm learning python.\n")
file.write("woking with file.\n")
file.close()
file=open("first_file.text","r")
content=file.read()
print(content)
file.close()